import { NeroWorkerPool } from './neroWorkerPool.js';
import { NeroDelegationAggregator } from './neroDelegationAggregator.js';
const SAFE={web_search:false,memory_read:false,memory_write:false,whatsapp_send:false,file_write:false,run_code:false,runtime_control:false,group_admin:false,delegation:false};
const ROLES={web:{workerId:'web',role:'web researcher',permissions:{...SAFE,web_search:true},task:'Find current, relevant evidence for the request. Search only; do not answer the user.'},analyst:{workerId:'analyst',role:'analyst',permissions:{...SAFE},task:'Analyze the request using only assigned context. Identify strongest conclusions and trade-offs.'},critic:{workerId:'critic',role:'critic',permissions:{...SAFE},task:'Stress-test likely conclusions. Identify ambiguity, contradictions, missing evidence, and failure modes.'}};
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
export class NeroDelegator {
  constructor({workerPool=null,aggregator=null}={}){this.workerPool=workerPool||new NeroWorkerPool();this.aggregator=aggregator||new NeroDelegationAggregator();}
  shouldDelegate(plan={}){return plan?.delegation===true&&plan?.delegationContract?.enabled===true&&plan?.delegationContract?.workers?.length>0;}
  buildSpecs({request,context='',plan={},webSearch=null,runModel=null}={}){if(!this.shouldDelegate(plan))return [];const c=plan.delegationContract,shared=clean(context).slice(0,c.contextChars);return c.workers.slice(0,c.maxWorkers).map((spec,i)=>{const role=spec.role||['web','analyst','critic'][i]||'analyst',r=ROLES[role]||ROLES.analyst;return {workerId:r.workerId,role:r.role,task:r.task+' Parent request: '+clean(request),context:shared,permissions:{...SAFE,...r.permissions,...(spec.permissions||{}),delegation:false,whatsapp_send:false,memory_write:false,file_write:false,run_code:false,runtime_control:false,group_admin:false},maxTokens:spec.maxTokens,maxOutputChars:c.maxResultCharsPerWorker,timeoutMs:c.workerTimeoutMs,runModel,webSearch};});}
  async run({request='',plan={},context='',webSearch=null,runModel=null,signal=null}={}){if(!this.shouldDelegate(plan))return {status:'disabled',text:'',workers:[],budget:null};const c=plan.delegationContract,pool=new NeroWorkerPool({maxWorkers:c.maxWorkers,totalTokenBudget:c.totalTokenBudget,totalWallTimeMs:c.totalWallTimeMs,maxResultChars:c.maxTotalResultChars}),result=await pool.run(this.buildSpecs({request,context,plan,webSearch,runModel}),{signal});return this.aggregator.aggregate({request,workers:result.workers,budget:result.budget});}
}
